spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/testdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: nona
    password: nona2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type: trace
    database-platform: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace